version: "3.9"
   
services:
  postgres:
    restart: always
    image: postgres
    container_name: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - chat_app_net
  chat-app:
    restart: always
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    command: bash -c "python manage.py migrate && 
                      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../:/chat-app
    ports:
      - "8000:8000"
      - "5432:5432"
    links:
      - postgres:postgres
    networks:
      - chat_app_net
    depends_on:
      - postgres

networks:
  chat_app_net:
    driver: bridge
